encoding: utf-8

# SEO相关信息
title: 胖哥
description: Pang.Ge
keywords: 胖哥,Pang.Ge,WeChat; QingHongJiao,Html,jekyll
author: Pang.Ge
footerText: 'Copyright © '

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: 'https://icp.me'
baseurl: '/tmaize-blog'

# logo 在 common.css，logo和"apple-touch-icon（在includes里head.html）ICO 已设置为同一张照片

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl: https://support.qq.com/product/

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
#   - title: 归类
#     url: /pages/categories.html
#   - title: 搜索
#     url: /pages/search.html
#   - title: 友链
#     url: /pages/links.html
#   - title: 留言
#     url: /pages/chat.html
#   - title: 关于
#     url: /pages/about.html
    
menu:
  - title: 首页
    url: /


# 点击页面文字冒出特效,不需要请设置为false 需要true
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
  - title: 文科中的技术宅
    url: https://www.townwang.com
  - title: Auuu Nya Blog
    url: http://mu1er.cn
  - title: 春风十里
    url: https://www.geek-era.com


